"""added archive_at to Order model 02/20

Revision ID: 134a055dd777
Revises: 814f1c16cc1a
Create Date: 2026-02-21 21:14:44.765306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '134a055dd777'
down_revision = '814f1c16cc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_at', sa.DateTime(timezone=True),nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('archive_at')

    # ### end Alembic commands ###
