"""added time_zone to team table

Revision ID: 7f66a23de2a6
Revises: 9c1f7d2ab4e3
Create Date: 2026-03-03 17:19:18.910376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f66a23de2a6'
down_revision = '9c1f7d2ab4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_costumer_team_id'))

    with op.batch_alter_table('notification_read', schema=None) as batch_op:
        batch_op.alter_column('seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('order_case', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('order_delivery_window', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_delivery_window_order_id_start_at'))

    with op.batch_alter_table('order_event', schema=None) as batch_op:
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('order_event_action', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('plan_event', schema=None) as batch_op:
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('plan_event_action', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('shopify_integrations', schema=None) as batch_op:
        batch_op.alter_column('connected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'time_zone',
                sa.String(length=64),
                nullable=False,
                server_default='UTC'
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('time_zone')

    with op.batch_alter_table('shopify_integrations', schema=None) as batch_op:
        batch_op.alter_column('connected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('plan_event_action', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('plan_event', schema=None) as batch_op:
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('order_event_action', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('order_event', schema=None) as batch_op:
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('order_delivery_window', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_delivery_window_order_id_start_at'), ['order_id', 'start_at'], unique=False)

    with op.batch_alter_table('order_case', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('notification_read', schema=None) as batch_op:
        batch_op.alter_column('seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_costumer_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###
