"""inital migration 02/20

Revision ID: 814f1c16cc1a
Revises: 
Create Date: 2026-02-20 17:17:09.496291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '814f1c16cc1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True)),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state'),
    sa.UniqueConstraint('team_id', 'state', name='uq_team_authstate')
    )
    op.create_table('shopify_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('shop_domain', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_counter', sa.Integer(), nullable=True),
    sa.Column('dead_letter_attempt', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopify_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopify_webhook_events_webhook_id'), ['webhook_id'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missing_to_configure', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('subscription', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=False)

    op.create_table('base_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_role_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_role_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_role_role_name'), ['role_name'], unique=False)

    op.create_table('email_smtp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('smtp_server', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=False),
    sa.Column('smtp_password', sa.String(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('max_per_session', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_smtp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_smtp_client_id'), ['client_id'], unique=False)

    op.create_table('item_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemposition_team_name')
    )
    with op.batch_alter_table('item_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_position_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_position_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_position_name'), ['name'], unique=False)

    op.create_table('item_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemproperty_team_name')
    )
    with op.batch_alter_table('item_property', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_property_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_property_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_property_name'), ['name'], unique=False)

    op.create_table('item_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('entry_point', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemstate_team_name')
    )
    with op.batch_alter_table('item_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_state_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_state_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_state_name'), ['name'], unique=False)

    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_itemtype_team_name')
    )
    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_type_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_type_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_type_name'), ['name'], unique=False)

    op.create_table('label_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('selected_variant', sa.String(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('ask_permission', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'event', 'channel', name='uq_label_template_team_event_channel')
    )
    with op.batch_alter_table('label_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_template_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_template_is_system'), ['is_system'], unique=False)

    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ask_permission', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('timestampt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'event', 'channel', name='uq_message_template_team_event_channel')
    )
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_template_client_id'), ['client_id'], unique=False)

    op.create_table('order_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_state_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_state_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_state_name'), ['name'], unique=False)

    op.create_table('plan_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_state_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_state_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_state_name'), ['name'], unique=False)

    op.create_table('twilio_mod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('twilio_account_sid', sa.String(), nullable=False),
    sa.Column('twilio_api_key_sid', sa.String(), nullable=False),
    sa.Column('twilio_api_key_secret_encrypted', sa.String(), nullable=False),
    sa.Column('sender_number', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twilio_mod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twilio_mod_client_id'), ['client_id'], unique=False)

    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('property_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_name'), ['name'], unique=False)

    op.create_table('delivery_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['plan_state.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_plan_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_plan_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_plan_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_plan_plan_type'), ['plan_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_plan_start_date'), ['start_date'], unique=False)

    op.create_table('type_property_association',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['item_property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['item_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'property_id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('base_role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_role_id'], ['base_role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_role_name'), ['role_name'], unique=False)

    op.create_table('date_range_access_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_model', sa.String(), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('date_range_access_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_date_range_access_rule_client_id'), ['client_id'], unique=False)

    op.create_table('international_shipping_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('carrier_name', sa.String(), nullable=True),
    sa.Column('delivery_plan_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_plan_id'], ['delivery_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_plan_id')
    )
    with op.batch_alter_table('international_shipping_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_international_shipping_plan_client_id'), ['client_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('order_plan_objective', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('external_order_id', sa.String(), nullable=True),
    sa.Column('external_source', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('tracking_link', sa.String(), nullable=True),
    sa.Column('client_first_name', sa.String(), nullable=True),
    sa.Column('client_last_name', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('client_primary_phone', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_secondary_phone', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('client_address', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('marketing_messages', sa.Boolean(), nullable=True),
    sa.Column('earliest_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_time_start', sa.String(), nullable=True),
    sa.Column('preferred_time_end', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_state_id', sa.Integer(), nullable=True),
    sa.Column('delivery_plan_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_plan_id'], ['delivery_plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_state_id'], ['order_state.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index('ix_order_client_address_gin', ['client_address'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_address_tsvector', [sa.literal_column("to_tsvector('simple', client_address::text)")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_order_client_email'), ['client_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_client_first_name'), ['client_first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_client_last_name'), ['client_last_name'], unique=False)
        batch_op.create_index('ix_order_client_primary_phone_gin', ['client_primary_phone'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_order_client_secondary_phone_gin', ['client_secondary_phone'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_order_earliest_delivery_date'), ['earliest_delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_external_order_id'), ['external_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_external_source'), ['external_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_latest_delivery_date'), ['latest_delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_plan_objective'), ['order_plan_objective'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_tracking_link'), ['tracking_link'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_tracking_number'), ['tracking_number'], unique=False)

    op.create_table('order_state_transition_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('allowed_state_id', sa.Integer(), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allowed_state_id'], ['order_state.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_state_transition_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_state_transition_rule_client_id'), ['client_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('profile_picture', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('old_team_id', sa.Integer(), nullable=True),
    sa.Column('old_role_id', sa.Integer(), nullable=True),
    sa.Column('show_app_tutorial', sa.Boolean(), nullable=True),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('article_number', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_position_id', sa.Integer(), nullable=True),
    sa.Column('item_state_id', sa.Integer(), nullable=True),
    sa.Column('page_link', sa.String(), nullable=True),
    sa.Column('dimension_depth', sa.Integer(), nullable=True),
    sa.Column('dimension_height', sa.Integer(), nullable=True),
    sa.Column('dimension_width', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_position_id'], ['item_position.id'], ),
    sa.ForeignKeyConstraint(['item_state_id'], ['item_state.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_article_number'), ['article_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_reference_number'), ['reference_number'], unique=False)

    op.create_table('local_delivery_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('delivery_plan_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_plan_id'], ['delivery_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_plan_id')
    )
    with op.batch_alter_table('local_delivery_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_delivery_plan_client_id'), ['client_id'], unique=False)

    op.create_table('order_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('from_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('to_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_audit_log_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_log_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_log_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_log_order_id'), ['order_id'], unique=False)

    op.create_table('order_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True)),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_case_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_case_order_id'), ['order_id'], unique=False)

    op.create_table('order_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True)),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_event_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_event_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_event_order_id'), ['order_id'], unique=False)

    op.create_table('order_state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('from_state_id', sa.Integer(), nullable=True),
    sa.Column('to_state_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_state_id'], ['order_state.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['to_state_id'], ['order_state.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_state_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_state_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_state_history_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_state_history_order_id'), ['order_id'], unique=False)

    op.create_table('plan_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True)),
    sa.Column('delivery_plan_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_plan_id'], ['delivery_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_event_delivery_plan_id'), ['delivery_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_event_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_event_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('shopify_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True)),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'shop', name='uq_team_shop')
    )
    op.create_table('store_pickup_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('pickup_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_plan_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['delivery_plan_id'], ['delivery_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_plan_id')
    )
    with op.batch_alter_table('store_pickup_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_pickup_plan_client_id'), ['client_id'], unique=False)

    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('from_team_name', sa.String(), nullable=False),
    sa.Column('target_username', sa.String(), nullable=False),
    sa.Column('target_email', sa.String(), nullable=False),
    sa.Column('user_role_name', sa.String(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invites_client_id'), ['client_id'], unique=False)

    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('travel_mode', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('cost_per_hour', sa.Float(), nullable=True),
    sa.Column('cost_per_kilometer', sa.Float(), nullable=True),
    sa.Column('travel_duration_limit', sa.Integer(), nullable=True),
    sa.Column('route_distance_limit', sa.Integer(), nullable=True),
    sa.Column('max_load', sa.Integer(), nullable=True),
    sa.Column('min_load', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_name'), ['name'], unique=False)

    op.create_table('case_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_case_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_case_id'], ['order_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_chat_client_id'), ['client_id'], unique=False)

    op.create_table('order_event_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True)),
    sa.Column('updated_at', sa.DateTime(timezone=True)),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['order_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'action_name', name='uq_order_event_action_event_name')
    )
    with op.batch_alter_table('order_event_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_event_action_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_event_action_status'), ['status'], unique=False)

    op.create_table('plan_event_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True)),
    sa.Column('updated_at', sa.DateTime(timezone=True)),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['plan_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'action_name', name='uq_plan_event_action_event_name')
    )
    with op.batch_alter_table('plan_event_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_event_action_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_event_action_status'), ['status'], unique=False)

    op.create_table('route_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_distance_meters', sa.Integer(), nullable=True),
    sa.Column('total_travel_time_seconds', sa.Integer(), nullable=True),
    sa.Column('expected_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_route_warnings', sa.Boolean(), nullable=True),
    sa.Column('route_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('end_location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('route_end_strategy', sa.Enum('round_trip', 'custom_end_address', 'end_at_last_stop', name='route_end_strategy'), nullable=False),
    sa.Column('set_start_time', sa.String(), nullable=True),
    sa.Column('set_end_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('is_optimized', sa.Enum('optimize', 'partial optimize', 'not optimize', name='is_optimized'), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('local_delivery_plan_id', sa.Integer(), nullable=False),
    sa.Column('route_polyline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['local_delivery_plan_id'], ['local_delivery_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_solution_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_solution_local_delivery_plan_id'), ['local_delivery_plan_id'], unique=False)

    op.create_table('notification_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('reader_name', sa.String(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True)),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_chat_id'], ['case_chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_read', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_read_client_id'), ['client_id'], unique=False)

    op.create_table('route_solution_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('route_solution_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('service_duration', sa.String(), nullable=True),
    sa.Column('in_range', sa.Boolean(), nullable=True),
    sa.Column('stop_order', sa.Integer(), nullable=True),
    sa.Column('reason_was_skipped', sa.String(), nullable=True),
    sa.Column('has_constraint_violation', sa.Boolean(), nullable=True),
    sa.Column('constraint_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eta_status', sa.Enum('valid', 'estimated', 'stale', name='eta_status'), nullable=False),
    sa.Column('expected_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_solution_id'], ['route_solution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_solution_stop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_solution_stop_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_solution_stop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_solution_stop_client_id'))

    op.drop_table('route_solution_stop')
    with op.batch_alter_table('notification_read', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_read_client_id'))

    op.drop_table('notification_read')
    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_solution_local_delivery_plan_id'))
        batch_op.drop_index(batch_op.f('ix_route_solution_client_id'))

    op.drop_table('route_solution')
    with op.batch_alter_table('plan_event_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_event_action_status'))
        batch_op.drop_index(batch_op.f('ix_plan_event_action_event_id'))

    op.drop_table('plan_event_action')
    with op.batch_alter_table('order_event_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_event_action_status'))
        batch_op.drop_index(batch_op.f('ix_order_event_action_event_id'))

    op.drop_table('order_event_action')
    with op.batch_alter_table('case_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_chat_client_id'))

    op.drop_table('case_chat')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_name'))
        batch_op.drop_index(batch_op.f('ix_vehicle_is_system'))
        batch_op.drop_index(batch_op.f('ix_vehicle_client_id'))

    op.drop_table('vehicle')
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invites_client_id'))

    op.drop_table('team_invites')
    with op.batch_alter_table('store_pickup_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_pickup_plan_client_id'))

    op.drop_table('store_pickup_plan')
    op.drop_table('shopify_integrations')
    with op.batch_alter_table('plan_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_plan_event_event_name'))
        batch_op.drop_index(batch_op.f('ix_plan_event_delivery_plan_id'))

    op.drop_table('plan_event')
    with op.batch_alter_table('order_state_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_state_history_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_state_history_client_id'))
        batch_op.drop_index(batch_op.f('ix_order_state_history_changed_at'))

    op.drop_table('order_state_history')
    with op.batch_alter_table('order_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_event_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_order_event_event_name'))

    op.drop_table('order_event')
    with op.batch_alter_table('order_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_case_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_case_client_id'))

    op.drop_table('order_case')
    with op.batch_alter_table('order_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_audit_log_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_audit_log_field_name'))
        batch_op.drop_index(batch_op.f('ix_order_audit_log_client_id'))
        batch_op.drop_index(batch_op.f('ix_order_audit_log_changed_at'))

    op.drop_table('order_audit_log')
    with op.batch_alter_table('local_delivery_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_delivery_plan_client_id'))

    op.drop_table('local_delivery_plan')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_reference_number'))
        batch_op.drop_index(batch_op.f('ix_item_is_system'))
        batch_op.drop_index(batch_op.f('ix_item_client_id'))
        batch_op.drop_index(batch_op.f('ix_item_article_number'))

    op.drop_table('item')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_client_id'))

    op.drop_table('user')
    with op.batch_alter_table('order_state_transition_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_state_transition_rule_client_id'))

    op.drop_table('order_state_transition_rule')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_tracking_number'))
        batch_op.drop_index(batch_op.f('ix_order_tracking_link'))
        batch_op.drop_index(batch_op.f('ix_order_reference_number'))
        batch_op.drop_index(batch_op.f('ix_order_order_plan_objective'))
        batch_op.drop_index(batch_op.f('ix_order_latest_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_order_external_source'))
        batch_op.drop_index(batch_op.f('ix_order_external_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_earliest_delivery_date'))
        batch_op.drop_index('ix_order_client_secondary_phone_gin', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_primary_phone_gin', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_order_client_last_name'))
        batch_op.drop_index(batch_op.f('ix_order_client_id'))
        batch_op.drop_index(batch_op.f('ix_order_client_first_name'))
        batch_op.drop_index(batch_op.f('ix_order_client_email'))
        batch_op.drop_index('ix_order_client_address_tsvector', postgresql_using='gin')
        batch_op.drop_index('ix_order_client_address_gin', postgresql_using='gin')

    op.drop_table('order')
    with op.batch_alter_table('international_shipping_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_international_shipping_plan_client_id'))

    op.drop_table('international_shipping_plan')
    with op.batch_alter_table('date_range_access_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_date_range_access_rule_client_id'))

    op.drop_table('date_range_access_rule')
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_role_name'))
        batch_op.drop_index(batch_op.f('ix_user_role_is_system'))
        batch_op.drop_index(batch_op.f('ix_user_role_client_id'))

    op.drop_table('user_role')
    op.drop_table('type_property_association')
    with op.batch_alter_table('delivery_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_plan_start_date'))
        batch_op.drop_index(batch_op.f('ix_delivery_plan_plan_type'))
        batch_op.drop_index(batch_op.f('ix_delivery_plan_label'))
        batch_op.drop_index(batch_op.f('ix_delivery_plan_end_date'))
        batch_op.drop_index(batch_op.f('ix_delivery_plan_client_id'))

    op.drop_table('delivery_plan')
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_name'))
        batch_op.drop_index(batch_op.f('ix_warehouse_client_id'))

    op.drop_table('warehouse')
    with op.batch_alter_table('twilio_mod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twilio_mod_client_id'))

    op.drop_table('twilio_mod')
    with op.batch_alter_table('plan_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_state_name'))
        batch_op.drop_index(batch_op.f('ix_plan_state_is_system'))
        batch_op.drop_index(batch_op.f('ix_plan_state_client_id'))

    op.drop_table('plan_state')
    with op.batch_alter_table('order_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_state_name'))
        batch_op.drop_index(batch_op.f('ix_order_state_is_system'))
        batch_op.drop_index(batch_op.f('ix_order_state_client_id'))

    op.drop_table('order_state')
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_template_client_id'))

    op.drop_table('message_template')
    with op.batch_alter_table('label_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_template_is_system'))
        batch_op.drop_index(batch_op.f('ix_label_template_client_id'))

    op.drop_table('label_template')
    with op.batch_alter_table('item_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_type_name'))
        batch_op.drop_index(batch_op.f('ix_item_type_is_system'))
        batch_op.drop_index(batch_op.f('ix_item_type_client_id'))

    op.drop_table('item_type')
    with op.batch_alter_table('item_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_state_name'))
        batch_op.drop_index(batch_op.f('ix_item_state_is_system'))
        batch_op.drop_index(batch_op.f('ix_item_state_client_id'))

    op.drop_table('item_state')
    with op.batch_alter_table('item_property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_property_name'))
        batch_op.drop_index(batch_op.f('ix_item_property_is_system'))
        batch_op.drop_index(batch_op.f('ix_item_property_client_id'))

    op.drop_table('item_property')
    with op.batch_alter_table('item_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_position_name'))
        batch_op.drop_index(batch_op.f('ix_item_position_is_system'))
        batch_op.drop_index(batch_op.f('ix_item_position_client_id'))

    op.drop_table('item_position')
    with op.batch_alter_table('email_smtp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_smtp_client_id'))

    op.drop_table('email_smtp')
    with op.batch_alter_table('base_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_role_role_name'))
        batch_op.drop_index(batch_op.f('ix_base_role_is_system'))
        batch_op.drop_index(batch_op.f('ix_base_role_client_id'))

    op.drop_table('base_role')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_name'))
        batch_op.drop_index(batch_op.f('ix_team_client_id'))

    op.drop_table('team')
    with op.batch_alter_table('shopify_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_webhook_events_webhook_id'))

    op.drop_table('shopify_webhook_events')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
