"""added service time to route solution and route solution stop, added operation_type to Order

Revision ID: e41b22f934ad
Revises: b2e4d9f6c1aa
Create Date: 2026-03-06 23:44:07.314998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e41b22f934ad'
down_revision = 'b2e4d9f6c1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_type', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_operation_type'), ['operation_type'], unique=False)

    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stops_service_time', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))

    with op.batch_alter_table('route_solution_stop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_time', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_solution_stop', schema=None) as batch_op:
        batch_op.drop_column('service_time')

    with op.batch_alter_table('route_solution', schema=None) as batch_op:
        batch_op.drop_column('stops_service_time')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_operation_type'))
        batch_op.drop_column('operation_type')

    # ### end Alembic commands ###
