IS_OPTIMIZED_OPTIMIZE = "optimize"
IS_OPTIMIZED_PARTIAL = "partial optimize"
IS_OPTIMIZED_NOT_OPTIMIZED = "not optimize"

IS_OPTIMIZED_VALUES = (
    IS_OPTIMIZED_OPTIMIZE,
    IS_OPTIMIZED_PARTIAL,
    IS_OPTIMIZED_NOT_OPTIMIZED,
)
