from Delivery_app_BK.services.domain.user import ADMIN_APP_SCOPE, DRIVER_APP_SCOPE

SERVER_EVENT_REALTIME_EVENT = "realtime:event"
SERVER_EVENT_REALTIME_ERROR = "realtime:error"
SERVER_EVENT_DRIVER_LOCATION_UPDATED = "driver_location.updated"
SERVER_EVENT_DRIVER_LOCATION_SNAPSHOT = "driver_location.snapshot"
SERVER_EVENT_EXTERNAL_FORM_RECEIVED = "external_form:received"
SERVER_EVENT_EXTERNAL_FORM_REQUESTED = "external_form:requested"
SERVER_EVENT_CLIENT_FORM_SUBMITTED = "client_form:submitted"
SERVER_EVENT_NOTIFICATION_EVENT = "notification:event"
SERVER_EVENT_NOTIFICATION_SNAPSHOT = "notification:snapshot"

CLIENT_EVENT_SUBSCRIBE = "realtime:subscribe"
CLIENT_EVENT_UNSUBSCRIBE = "realtime:unsubscribe"
CLIENT_EVENT_DRIVER_LOCATION_PUBLISH = "driver_location:publish"
CLIENT_EVENT_NOTIFICATION_MARK_READ = "notification:mark_read"
CLIENT_EVENT_EXTERNAL_FORM_JOIN_USER = "external_form:join_user"
CLIENT_EVENT_EXTERNAL_FORM_LEAVE_USER = "external_form:leave_user"
CLIENT_EVENT_EXTERNAL_FORM_SUBMIT_USER = "external_form:submit_user"
CLIENT_EVENT_EXTERNAL_FORM_REQUEST_USER = "external_form:request_user"

CHANNEL_TEAM_ORDERS = "team_orders"
CHANNEL_TEAM_ORDER_CASES = "team_order_cases"
CHANNEL_TEAM_ADMIN = "team_admin"
CHANNEL_ROUTE_ORDERS = "route_orders"
CHANNEL_TEAM_DRIVER_LIVE = "team_driver_live"
CHANNEL_ORDER_CHAT = "order_chat"
CHANNEL_TEAM_MEMBERS = "team_members"

ALLOWED_CHANNELS = {
    CHANNEL_TEAM_ADMIN,
    CHANNEL_TEAM_ORDERS,
    CHANNEL_TEAM_ORDER_CASES,
    CHANNEL_ROUTE_ORDERS,
    CHANNEL_TEAM_DRIVER_LIVE,
    CHANNEL_ORDER_CHAT,
    CHANNEL_TEAM_MEMBERS,
}

ALLOWED_APP_SCOPES_BY_CHANNEL = {
    CHANNEL_TEAM_ADMIN: {ADMIN_APP_SCOPE},
    CHANNEL_TEAM_ORDERS: {ADMIN_APP_SCOPE, DRIVER_APP_SCOPE},
    CHANNEL_TEAM_ORDER_CASES: {ADMIN_APP_SCOPE, DRIVER_APP_SCOPE},
    CHANNEL_ROUTE_ORDERS: {ADMIN_APP_SCOPE, DRIVER_APP_SCOPE},
    CHANNEL_TEAM_DRIVER_LIVE: {ADMIN_APP_SCOPE, DRIVER_APP_SCOPE},
    CHANNEL_ORDER_CHAT: {ADMIN_APP_SCOPE, DRIVER_APP_SCOPE},
    CHANNEL_TEAM_MEMBERS: {DRIVER_APP_SCOPE},
}

BUSINESS_EVENT_ORDER_CREATED = "order.created"
BUSINESS_EVENT_ORDER_UPDATED = "order.updated"
BUSINESS_EVENT_ORDER_STATE_CHANGED = "order.state_changed"
BUSINESS_EVENT_ORDER_CASE_CREATED = "order_case.created"
BUSINESS_EVENT_ORDER_CASE_UPDATED = "order_case.updated"
BUSINESS_EVENT_ORDER_CASE_STATE_CHANGED = "order_case.state_changed"
BUSINESS_EVENT_ORDER_CHAT_MESSAGE_CREATED = "order_chat.message_created"

# Delivery Plan Events
BUSINESS_EVENT_DELIVERY_PLAN_CREATED = "delivery_plan.created"
BUSINESS_EVENT_DELIVERY_PLAN_UPDATED = "delivery_plan.updated"
BUSINESS_EVENT_DELIVERY_PLAN_DELETED = "delivery_plan.deleted"

# Local Delivery Plan Events
BUSINESS_EVENT_LOCAL_DELIVERY_PLAN_UPDATED = "local_delivery_plan.updated"
BUSINESS_EVENT_ROUTE_GROUP_UPDATED = BUSINESS_EVENT_LOCAL_DELIVERY_PLAN_UPDATED

# Route Solution Events
BUSINESS_EVENT_ROUTE_SOLUTION_CREATED = "route_solution.created"
BUSINESS_EVENT_ROUTE_SOLUTION_UPDATED = "route_solution.updated"
BUSINESS_EVENT_ROUTE_SOLUTION_DELETED = "route_solution.deleted"

# Route Solution Stop Events
BUSINESS_EVENT_ROUTE_SOLUTION_STOP_UPDATED = "route_solution_stop.updated"

DEFAULT_EVENT_VERSION = "1"
